[Interface]
PrivateKey = EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE=
Address = 10.10.10.1/24
ListenPort = 51821
MTU = 1420

# Site B
[Peer]
PublicKey = FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF=
AllowedIPs = 10.10.10.2/32, 192.168.50.0/24
PersistentKeepalive = 15
